# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_auto_20180704_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_ip', models.CharField(max_length=50)),
                ('ext_ip', models.CharField(max_length=50)),
                ('host_ip', models.CharField(max_length=50)),
                ('vm_name', models.CharField(max_length=50)),
                ('vm_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='cabinet',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='server',
        ),
    ]
